# **Numpy**
NumPy es una librería de propósito general para el procesamiento de arrays.
Proporciona un objeto de array multidimensional de alto rendimiento y herramientas para trabajar con estos arrays.
<BR>

El nombre NumPy proviene de “Numerical Python” (Python Numérico).
<BR>

Además, incluye funciones para trabajar en los dominios de:
* Álgebra lineal
* Matrices


El objeto array en NumPy se llama ndarray (N-dimensional array).
Este objeto viene acompañado de muchas funciones que facilitan enormemente el trabajo con los ndarray.

**Por qué es más rápido que las listas tradicionales de Python?**
<BR>
Los arrays de NumPy se almacenan en un único espacio continuo en memoria, a diferencia de las listas, por lo que los procesos pueden acceder y manipularlos de manera muy eficiente.
<BR>
Además, están optimizados para funcionar con las arquitecturas de CPU más recientes.

## Importamos NumPy con el alias np

In [ ]:
import numpy as np

## Ver la versión

In [ ]:
print(np.__version__)

## Documentación oficial






[Acceder aquí](https://numpy.org/doc/)

## Crear Arrays en NumPy
NumPy se utiliza para trabajar con arrays.

El objeto array en NumPy se llama ndarray.

Podemos crear un objeto ndarray de NumPy usando la función array().

In [ ]:
numeros = list([12,20,30,40,50,60])
print(numeros)
print(type(numeros))

In [21]:
for indice in range(len(numeros)):
  print(numeros[indice])

13
21
31
41
51
61


In [ ]:
arr = np.array([12,20,30,40,50,60]) #np.array()

print(arr)
print(type(arr))

Podemos pasar una lista, tupla o cualquier objeto similar a un array al método array(), y será convertido en un ndarray.

In [10]:
arr =np.array((10,20,30,40,50,60))
print(arr)
print(type(arr))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


## Crear un array dentro de un rango específico

El método np.arange() puede usarse en lugar del método np.array(range()).

In [22]:
# np.arange(start, stop, step)
arr = np.arange(3, 21, 1)
print(arr)
print(type(arr))

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>


## Crear un array de números equidistantes dentro de un rango específico

np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) tiene 5 parámetros:

start: número de inicio (inclusive)

stop: número final (inclusive, a menos que endpoint esté establecido en False)

num_of_elements: cantidad de elementos que contendrá el array

endpoint: valor booleano que indica si el número stop está incluido o no

retstep: valor booleano que indica si se debe devolver el tamaño del paso

np.linspace se usa mucho cuando queremos generar los valores del eje x (ordenada)

In [15]:
arr, step_size = np.linspace(0, 5, 10, endpoint=True, retstep=True)
print(arr)
print(arr.size)
print('The step size is ' + str(step_size))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
10
The step size is 0.5555555555555556


## Crear un array de valores aleatorios con una forma determinada

El método np.random.rand() devuelve valores en el rango [0, 1).

In [18]:
# arr = np.random.rand(2, 3)
arr = np.round(np.random.rand(2, 3), 2)
print(arr)

[[0.51 0.99 0.06]
 [0.26 0.6  0.47]]


## Crear un array de ceros

np.zeros(): crea un array de solo ceros con la forma especificada

np.zeros_like(): crea un array de solo ceros con la misma forma y tipo de dato que el array dado como entrada

In [23]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


## Crear un array de unos

np.ones(): crea un array de solo unos con la forma especificada

np.ones_like(): crea un array de solo unos con la misma forma y tipo de dato que el array dado como entrada

In [25]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
arr = [[1,2,3], [4,5,6]] # matriz de 2 x 3
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int64


## Crear un array vacío con una forma determinada

np.empty(): crea un array de valores vacíos con la forma especificada

np.empty_like(): crea un array de valores vacíos con la misma forma y tipo de dato que el array dado como entrada

Ten en cuenta que los valores iniciales no están necesariamente establecidos en cero.

Son simplemente valores basura que ya estaban almacenados en direcciones de memoria aleatorias.

In [ ]:
empty = np.empty((2,2))
print(empty)
print(empty.dtype)

In [ ]:
newarr = np.array([[10,20,30], [40,50,60]], dtype=np.int64)
empty = np.empty_like(newarr)
print(empty)
print('Data Type: ' + str(empty.dtype))

## Crear un array de valores constantes con una forma determinada

np.full(): crea un array de valores constantes con la forma especificada

np.full_like(): crea un array de valores constantes con la misma forma y tipo de dato que el array dado como entrada

In [ ]:
full = np.full((4,4), 4)
print(full)

In [ ]:
arr = np.array([[1,2], [3,4]], dtype=np.int64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

## **Create an identity matrix of given size**
- ```np.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [ ]:
identity_matrix = np.eye(4)
print(identity_matrix)
print(type(identity_matrix))

In [ ]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=1) # default k = 0
print(identity_matrix)

In [ ]:
identity_matrix = np.identity(5)
print(identity_matrix)
print(type(identity_matrix))

## No tiene que ser una matriz cuadrada

In [ ]:
arr = np.random.rand(5,3)
print(arr)

# **Dimensions in Arrays**
A **dimension** in arrays is **one level** of **array depth** (nested arrays).

**Nested array:** are arrays that **have arrays as their elements.**

## Arrays 0-D

Los arrays 0-D, o escalares, son los elementos dentro de un array.

Cada valor en un array es un array 0-D.

In [27]:
#create 0-D array with value '10'

arr=np.array('10')
print(arr)

10


## Arrays unidimensionales (1-D)

Un array que tiene arrays de 0 dimensiones (0-D) como sus elementos se llama unidimensional o array 1-D.

Estos son los arrays más comunes y básicos.

In [28]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## Arrays bidimensionales (2-D)

Un array que tiene arrays unidimensionales (1-D) como sus elementos se llama array 2-D.

Estos se utilizan frecuentemente para representar matrices o tensores de segundo orden.

NumPy tiene todo un submódulo dedicado a las operaciones con matrices, llamado numpy.mat.

In [29]:
arr= np.array([[10,20,30],[40,50,60]])
print(arr)

[[10 20 30]
 [40 50 60]]


## Arrays tridimensionales (3-D)

Un array que tiene arrays 2-D (matrices) como sus elementos se llama array 3-D.

Estos se utilizan frecuentemente para representar un tensor de tercer orden.

In [30]:
arr =np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])
print(arr)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]


##¿Cómo verificar el número de dimensiones?

Los arrays de NumPy proporcionan el atributo ndim, que devuelve un número entero indicando cuántas dimensiones tiene el array.

In [31]:
array_0d = np.array(42)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(f"El número de dimensiones del array es :" ,array_0d.ndim)
print(f"El número de dimensiones del array es :" ,array_1d.ndim)
print(f"El número de dimensiones del array es :" ,array_2d.ndim)
print(f"El número de dimensiones del array es :" ,array_3d.ndim)

El número de dimensiones del array es : 0
El número de dimensiones del array es : 1
El número de dimensiones del array es : 2
El número de dimensiones del array es : 3


## Inspeccionar información general de un array

In [32]:
print(np.info(array_2d))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2a910a0
byteorder:  little
byteswap:  False
type: int64
None


# Tipos de datos en NumPy

NumPy tiene algunos tipos de datos adicionales, y se refiere a los tipos de datos con un solo carácter, como i para enteros, u para enteros sin signo, etc.

**i** entero

**b** booleano

**u** entero sin signo

**f** número de punto flotante

**c** número complejo de punto flotante

**m** diferencia de tiempo (timedelta)

**M** fecha y hora (datetime)

**O** objeto (object)

**S** cadena de caracteres (string - ASCII)

**U** cadena Unicode

**V** bloque fijo de memoria para otro tipo (void)

[NumPy Data Types](https://numpy.org/doc/2.3/user/basics.types.html)

## Verificar el tipo de dato de un array

El objeto array de NumPy tiene una propiedad llamada dtype que devuelve el tipo de dato del array.

In [34]:
arr = np.array([1, 2, 3, 4.6])

print(arr.dtype)

float64


In [36]:
arr = np.array(['apple', 'banana', 'cherry', 3])

print(arr.dtype)

<U21


## Crear arrays con un tipo de dato definido

La función array() puede recibir un argumento opcional llamado dtype, que nos permite definir el tipo de dato esperado para los elementos del array.

In [42]:
# arr = np.array([1, 2, 3, 4.5], dtype=str)
arr = np.array([1, 2, 3, 4], dtype="S") # pueden usar i, f, etc

print(arr)
print(arr.dtype)  #los datos son convertidos a string

[b'1' b'2' b'3' b'4']
|S1


## ¿Qué pasa si un valor no se puede convertir?

Si se especifica un tipo al cual los elementos no pueden ser convertidos, entonces NumPy lanzará un ValueError.

ValueError: En Python, un ValueError se lanza cuando el tipo del argumento pasado a una función es inesperado o incorrecto.

In [46]:
arr = np.array(['a', '2', '3'], dtype='i') #obtenemos error al querer convertir un str a int

['a' '2' '3' '4']


## Convertir el tipo de dato en arrays existentes

La mejor forma de cambiar el tipo de dato de un array existente es hacer una copia del array utilizando el método astype().
La función astype() crea una copia del array y te permite especificar el tipo de dato como parámetro.

El tipo de dato puede especificarse usando una cadena de texto, como 'f' para flotante, 'i' para entero, etc.

O también se puede usar el tipo de dato directamente, como float para flotante e int para entero.

In [51]:
arr=np.array((1.2, 20.2, 30.9))
print(arr)
print(arr.dtype)

arr2=arr.astype(int) # ("i") int32 / (int) int64
print(arr2)
print(arr2.dtype)

[ 1.2 20.2 30.9]
float64
[ 1 20 30]
int64


In [52]:
arr=np.array((1.2,20.2 ,30.3))
print(arr)
print(arr.dtype)


arr2=arr.astype(int)
print(arr2)
print(arr2.dtype)

[ 1.2 20.2 30.3]
float64
[ 1 20 30]
int64


## Indexación en Arrays de NumPy
Acceder a los elementos del array:

La indexación en arrays es lo mismo que acceder a un elemento del array.

Puedes acceder a un elemento del array refiriéndote a su número de índice.

Los índices en los arrays de NumPy comienzan en 0, lo que significa que el primer elemento tiene el índice 0, el segundo el índice 1, y así sucesivamente.

In [54]:
#Acceder al primer elemento

arr= np.array([10,20,30,40,50,60,70,80,90,100])

print(arr[-1]) # 100
print(arr[0]) # 0

100


In [ ]:
#Accedemos al segundo

arr= np.array([10,20,30,40,50,60,70,80,90,100])

print(arr[1])

In [ ]:
# Obtén el tercer y cuarto elemento del siguiente array y súmalos.

arr= np.array([10,20,30,40,50,60,70,80,90,100])

print(arr[2]+arr[3])

## Acceder a arrays 2-D

Para acceder a elementos de arrays 2-D, podemos usar enteros separados por comas que representan la dimensión (fila) y el índice del elemento (columna).

El índice de la dimensión también comienza en 0

In [57]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
np.info(arr)
print(f"El primer elemento de la primera dimensión {arr[0,0]}") # matriz[fila][columna]

class:  ndarray
shape:  (2, 5)
strides:  (40, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2a79020
byteorder:  little
byteswap:  False
type: int64
El primer elemento de la primera dimensión 10


In [61]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(f"El primer elemento de la segunda dimensión {arr[1,0]}")
print(f"El primer elemento de la segunda dimensión {arr[1,2:]}") #[80  90 100]
print(f"El primer elemento de la segunda dimensión {arr[1,:3]}") #[60 70 80]

El primer elemento de la segunda dimensión 60
El primer elemento de la segunda dimensión [ 80  90 100]
El primer elemento de la segunda dimensión [60 70 80]


Revisar slicing para obtener subconjuntos

## **Negative Indexing**

>Use negative indexing to access an array from the end.

In [ ]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(f"Last element from first Dimension {arr[0,-1]}")

## Forma (Shape) de un array en NumPy

La forma de un array es la cantidad de elementos en cada dimensión.

Los arrays de NumPy tienen un atributo llamado shape que devuelve una tupla, donde cada índice representa la cantidad de elementos en la dimensión correspondiente.

In [ ]:
#Imprimir el shape de una array de 2D

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)  #SALIDA 2 ⇒ Dos elementos en la primera dimensión 4 ⇒ Cuatro elementos en la segunda dimensión

## Cambio de forma (Reshape) de arrays en NumPy

Al aplicar reshape podemos agregar o eliminar dimensiones o cambiar la cantidad de elementos en cada dimensión.

Convertir de 1-D a 2-D

La dimensión más externa tendrá 2 arrays, cada uno con 6 elementos.

In [ ]:
#Convierte el siguiente array 1-D con 12 elementos en un array 2-D.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 6)

print(newarr)

## Convertir de 1-D a 3-D

La dimensión más externa tendrá 2 arrays, que contienen 2 arrays cada uno, con 3 elementos cada uno.

In [ ]:
#Convierte el siguiente array 1-D con 12 elementos en un array 3-D.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,2,3)
print(newarr)

## ¿Podemos cambiar la forma (reshape) a cualquier forma?

Sí, siempre que la cantidad de elementos necesaria para el cambio de forma sea igual en ambas formas.

Podemos transformar un array 1-D de 8 elementos en un array 2-D con 2 filas de 4 elementos,
pero no podemos convertirlo en un array 2-D de 3 filas con 3 elementos, ya que eso requeriría 3 × 3 = 9 elementos.